name: beyonders_signup_login
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  url_launcher: ^6.1.11
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.5.0
  google_fonts: ^6.2.0
  shared_preferences: ^2.2.2
  geolocator: ^13.0.2
  excel: ^4.0.6
  path_provider: ^2.1.2
  path_provider_android: ^2.0.30


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/admin_profile.png
    - assets/Flux_Dev_i_need_3d_animation_images_for_initializing_of_a_app__0.jpg
    - assets/onboard2.jpeg
    - assets/Flux_Dev_i_need_3d_animation_images_for_initializing_of_a_app__2.jpg
    - assets/Flux_Dev_A_series_of_animated_images_showcasing_the_initializa_3.jpeg
    - assets/Flux_Dev_i_need_animation_images_for_initialzing_of_a_app_whic_1.jpg
